import { createBrowserRouter } from 'react-router-dom';
import { Layout } from '../components/layout';
import AdminLayout from '../components/admin/AdminLayout';
import {
  Home,
  Services,
  ServiceDetail,
  Portfolio,
  PortfolioDetail,
  About,
  Contact,
  Pricing,
  Blog,
  BlogPost,
  FAQ,
  Location,
  Start,
  ThankYou,
  NotFound,
  Process,
  CaseStudies,
  Awards,
  Partners,
  Industries,
  Industry,
  TehranAgency,
  WebProjectDetail,
} from '../pages';
import {
  Login as AdminLogin,
  Dashboard as AdminDashboard,
  Services as AdminServices,
  Portfolios as AdminPortfolios,
  Contacts as AdminContacts,
  Blog as AdminBlog,
  Clients as AdminClients,
  Industries as AdminIndustries,
  Packages as AdminPackages,
  Testimonials as AdminTestimonials,
  Reels as AdminReels,
  HomeCards as AdminHomeCards,
  WebProjects as AdminWebProjects,
  TeamMembers as AdminTeamMembers,
} from '../pages/admin';

export const router = createBrowserRouter([
  {
    path: '/',
    element: <Layout />,
    children: [
      { index: true, element: <Home /> },
      { path: 'services', element: <Services /> },
      { path: 'services/:slug', element: <ServiceDetail /> },
      { path: 'portfolio', element: <Portfolio /> },
      { path: 'portfolio/:portfolioId', element: <PortfolioDetail /> },
      { path: 'about', element: <About /> },
      { path: 'contact', element: <Contact /> },
      { path: 'pricing', element: <Pricing /> },
      { path: 'blog', element: <Blog /> },
      { path: 'blog/:slug', element: <BlogPost /> },
      { path: 'faq', element: <FAQ /> },
      { path: 'process', element: <Process /> },
      { path: 'case-studies', element: <CaseStudies /> },
      // { path: 'awards', element: <Awards /> }, // Hidden temporarily - page exists but not accessible
      { path: 'partners', element: <Partners /> },
      { path: 'industries', element: <Industries /> },
      { path: 'industries/:slug', element: <Industry /> },
      { path: 'tehran', element: <TehranAgency /> },
      { path: 'locations/:locationSlug', element: <Location /> },
      { path: 'web-projects/:slug', element: <WebProjectDetail /> },
      { path: 'start', element: <Start /> },
      { path: 'thank-you', element: <ThankYou /> },
      { path: '*', element: <NotFound /> },
    ],
  },
  {
    path: '/admin/login',
    element: <AdminLogin />,
  },
  {
    path: '/admin',
    element: <AdminLayout />,
    children: [
      { path: 'dashboard', element: <AdminDashboard /> },
      { path: 'services', element: <AdminServices /> },
      { path: 'home-cards', element: <AdminHomeCards /> },
      { path: 'web-projects', element: <AdminWebProjects /> },
      { path: 'portfolios', element: <AdminPortfolios /> },
      { path: 'contacts', element: <AdminContacts /> },
      { path: 'blog', element: <AdminBlog /> },
      { path: 'clients', element: <AdminClients /> },
      { path: 'industries', element: <AdminIndustries /> },
      { path: 'packages', element: <AdminPackages /> },
      { path: 'testimonials', element: <AdminTestimonials /> },
      { path: 'reels', element: <AdminReels /> },
      { path: 'team', element: <AdminTeamMembers /> },
    ],
  },
]);
